apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kanjis.fullname" . }}-api
  labels:
    {{- include "kanjis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kanjis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kanjis.selectorLabels" . | nindent 8 }}
        concern: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag}}"
          imagePullPolicy: {{ .Values.api.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
