apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "kanjis.fullname" . }}
  labels:
spec:
  rules:
    - http:
        paths:
        - path: /api
          backend: 
            serviceName: {{ include "kanjis.fullname" . }}-api
            servicePort: 80

