{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kanjis.serviceAccountName" . }}
  labels:
{{ include "kanjis.labels" . | nindent 4 }}
{{- end -}}
