apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanjis.fullname" . }}-api
  labels:
    {{- include "kanjis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kanjis.selectorLabels" . | nindent 4 }}
    concern: api
