apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanjis.fullname" . }}-byobu
  labels:
    {{- include "kanjis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "kanjis.selectorLabels" . | nindent 4 }}
    concern: byobu
